/*
 * API REST EXTERNA de interdoc
 * Conjunt de Serveis REST de interdoc per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.interdoc.apiexterna.client.api;

import es.caib.interdoc.apiexterna.client.services.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecuretatApi
 */
@Ignore
public class SecuretatApiTest {

    private final SecuretatApi api = new SecuretatApi();

    /**
     * Fa un ECHO
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void echoTest() throws ApiException {
        String echoInput = null;
        String response = api.echo(echoInput);

        // TODO: test validations
    }
}
