<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>es.caib.interdoc</groupId>
        <artifactId>interdoc</artifactId>
        <version>1.0.2</version>
    </parent>
    <artifactId>interdoc-plugins</artifactId>
    <packaging>pom</packaging>
    <name>Interdoc - Plugins</name>
    <description>Mòdul pare de Plugins de Interdoc</description>
    <modules>
        <module>interdoc_plugins_arxiu</module>
        <module>interdoc_plugins_firma_api</module>
		<module>interdoc_plugins_firma_apifirmasimple</module>
    </modules>
</project>
