# Propietats de configuració de SISTEMES de interdoc.
# La ubicació d'aquest fitxer s'ha de registrar mitjançant la propietat de sistema
# es.caib.interdoc.system.properties (veure apartat 3.5.2 dels estàndards)
# (el fitxer empra la codificació UTF-8)

## WS START
## Parámetros con la configuración del asistente de nuevas referencias para la conexión al webservice de obtenerReferenciaService. 
## Es necesario que el usuario esté dado de alta en Keycloak con el rol ITD_WS

#Props antics
#es.caib.interdoc.obtenerreferencia.wsdl=http://dev.caib.es/interdoc-ws-server/ObtenerReferenciaWsService/ObtenerReferenciaWs
#es.caib.interdoc.obtenerreferencia.usuari=interdoc
#es.caib.interdoc.obtenerreferencia.clau=interdoc

#Props nous
es.caib.interdoc.pluginsib.arxiu.endpoint=http://dev.caib.es/interdoc-ws-server/ObtenerReferenciaWsService/ObtenerReferenciaWs
es.caib.interdoc.pluginsib.arxiu.usuari=interdoc
es.caib.interdoc.pluginsib.arxiu.contrasenya=interdoc


## WS END
