-- DROP USER INTERDOC;

CREATE USER INTERDOC
-- IDENTIFIED BY <password>
;

CREATE TABLE "INTERDOC"."ITD_ACCES" 
   (	"ACCESID" NUMBER(19,0) NOT NULL ENABLE, 
	"IDENTIFICACIO" VARCHAR2(50), 
	"TIPUSIDENTIFICACIO" VARCHAR2(50), 
	"IP" VARCHAR2(20), 
	"DATACREACIO" TIMESTAMP (6), 
	"REFERENCIAID" NUMBER(19,0), 
	 PRIMARY KEY ("ACCESID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "INTERDOCTS" ;

ALTER TABLE "INTERDOC"."ITD_ACCES" ADD CONSTRAINT "ITD_ACCREF_REFID_FK" FOREIGN KEY ("REFERENCIAID")
	  REFERENCES "INTERDOC"."ITD_REFERENCIA" ("REFERENCIAID") ENABLE;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100760" ON "INTERDOC"."ITD_ACCES" ("ACCESID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS" ;
  CREATE INDEX "INTERDOC"."ITD_ACCES_REFERENCIAID_FK_I" ON "INTERDOC"."ITD_ACCES" ("REFERENCIAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_APLICACIO" 
   (	"APLICACIOID" NUMBER(19,0) NOT NULL ENABLE, 
	"USUARI" VARCHAR2(50), 
	"CLAU" VARCHAR2(100), 
	"NOM" VARCHAR2(255), 
	"CODIDIR3" VARCHAR2(50) NOT NULL ENABLE, 
	"DATACREACIO" TIMESTAMP (6), 
	"ESTAT" NUMBER(10,0), 
	 PRIMARY KEY ("APLICACIOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100763" ON "INTERDOC"."ITD_APLICACIO" ("APLICACIOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_ENTITAT" 
   (	"ENTITATID" NUMBER(19,0) NOT NULL ENABLE, 
	"NOM" VARCHAR2(255) NOT NULL ENABLE, 
	"CODIDIR3" VARCHAR2(50), 
	"DATACREACIO" TIMESTAMP (6), 
	"ACTIU" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ENTITATID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100767" ON "INTERDOC"."ITD_ENTITAT" ("ENTITATID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_FITXER" 
   (	"FITXERID" NUMBER(19,0) NOT NULL ENABLE, 
	"NOM" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPCIO" VARCHAR2(1000), 
	"MIME" VARCHAR2(255) NOT NULL ENABLE, 
	"TAMANY" NUMBER(19,0) NOT NULL ENABLE, 
	"DATACREACIO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"RUTA" VARCHAR2(255), 
	 PRIMARY KEY ("FITXERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100772" ON "INTERDOC"."ITD_FITXER" ("FITXERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_INFOARXIU" 
   (	"INFOARXIUID" NUMBER(19,0) NOT NULL ENABLE, 
	"ORIGINALFILEURL" VARCHAR2(255), 
	"CSV" VARCHAR2(255), 
	"CSVGENERATIONDEFINITION" VARCHAR2(255), 
	"CSVVALIDATIONWEB" VARCHAR2(255), 
	"ARXIUEXPEDIENTID" VARCHAR2(255), 
	"ARXIUDOCUMENTID" VARCHAR2(255), 
	"PRINTABLEURL" VARCHAR2(255), 
	"ENIFILEURL" VARCHAR2(255), 
	"VALIDATIONFILEURL" VARCHAR2(255), 
	"ESTATEXPEDIENT" VARCHAR2(5), 
	"REINTENTS" NUMBER(10,0), 
	 PRIMARY KEY ("INFOARXIUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100774" ON "INTERDOC"."ITD_INFOARXIU" ("INFOARXIUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_INFOSIGNATURA" 
   (	"INFOSIGNATURAID" NUMBER(19,0) NOT NULL ENABLE, 
	"SIGNOPERATION" NUMBER(10,0) NOT NULL ENABLE, 
	"SIGNTYPE" VARCHAR2(255) NOT NULL ENABLE, 
	"SIGNALGORITHM" VARCHAR2(255), 
	"SIGNMODE" NUMBER(10,0), 
	"SIGNATURESTABLELOCATION" NUMBER(10,0), 
	"TIMESTAMPINCLUDED" CHAR(1), 
	"POLICYINCLUDED" CHAR(1), 
	"ENITIPOFIRMA" VARCHAR2(255), 
	"ENIPERFILFIRMA" VARCHAR2(255), 
	"ENIROLFIRMA" VARCHAR2(255), 
	"ENISIGNERNAME" VARCHAR2(255), 
	"ENISIGNERADMINISTRATIONID" VARCHAR2(255), 
	"ENISIGNLEVEL" VARCHAR2(255), 
	"CHECKADMINISTRATIONIDOFSIGNER" CHAR(1), 
	"CHECKDOCUMENTMODIFICATIONS" CHAR(1), 
	"CHECKVALIDATIONSIGNATURE" CHAR(1), 
	"SIGNDATE" TIMESTAMP (6), 
	"signId" VARCHAR2(255), 
	"FILENAME" VARCHAR2(255), 
	"FILEMIME" VARCHAR2(255), 
	 PRIMARY KEY ("INFOSIGNATURAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100778" ON "INTERDOC"."ITD_INFOSIGNATURA" ("INFOSIGNATURAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_LOG" 
   (	"LOGID" NUMBER(19,0) NOT NULL ENABLE, 
	"DESCRIPCIO" CLOB, 
	"PETICIO" VARCHAR2(255), 
	"EXCEPCIO" CLOB, 
	"DATACREACIO" TIMESTAMP (6), 
	 PRIMARY KEY ("LOGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "INTERDOCTS" 
 LOB ("DESCRIPCIO") STORE AS SECUREFILE (
  TABLESPACE "INTERDOCTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("EXCEPCIO") STORE AS SECUREFILE (
  TABLESPACE "INTERDOCTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100780" ON "INTERDOC"."ITD_LOG" ("LOGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS" ;
  CREATE UNIQUE INDEX "INTERDOC"."SYS_IL0000242325C00004$$" ON "INTERDOC"."ITD_LOG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "INTERDOC"."SYS_IL0000242325C00002$$" ON "INTERDOC"."ITD_LOG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
;

CREATE TABLE "INTERDOC"."ITD_METADADA" 
   (	"METADADAID" NUMBER(19,0) NOT NULL ENABLE, 
	"NOM" VARCHAR2(255), 
	"VALOR" VARCHAR2(255), 
	"DATACREACIO" TIMESTAMP (6) NOT NULL ENABLE, 
	"REFERENCIAID" NUMBER(19,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("METADADAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "INTERDOCTS" ;

ALTER TABLE "INTERDOC"."ITD_METADADA" ADD CONSTRAINT "ITD_METREF_REFID_FK" FOREIGN KEY ("REFERENCIAID")
	  REFERENCES "INTERDOC"."ITD_REFERENCIA" ("REFERENCIAID") ENABLE;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100784" ON "INTERDOC"."ITD_METADADA" ("METADADAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS" ;
  CREATE INDEX "INTERDOC"."ITD_METADADA_REFERENCIAID_FK_I" ON "INTERDOC"."ITD_METADADA" ("REFERENCIAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_PETICIOATERCER" 
   (	"PETICIOID" NUMBER(19,0) NOT NULL ENABLE, 
	"CSVIDENTIFICADOR" VARCHAR2(255), 
	"ENIIDENTIFICADOR" VARCHAR2(255), 
	"CODIDIR3" VARCHAR2(20), 
	"RECUPERACIOORIGINAL" CHAR(1), 
	"DOCUMENTENI" VARCHAR2(255), 
	"NIF" VARCHAR2(50), 
	"TIPUSIDENTIFICACIO" NUMBER(10,0), 
	"IP" VARCHAR2(20), 
	"DATACREACIO" TIMESTAMP (6), 
	"ESTAT" NUMBER(10,0), 
	 PRIMARY KEY ("PETICIOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "INTERDOCTS" ;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100786" ON "INTERDOC"."ITD_PETICIOATERCER" ("PETICIOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_PLUGIN" 
   (	"PLUGINID" NUMBER(19,0) NOT NULL ENABLE, 
	"NOM" VARCHAR2(100), 
	"PROPIETATS" CLOB, 
	"CLASSE" VARCHAR2(255), 
	"DATACREACIO" TIMESTAMP (6) WITH TIME ZONE, 
	"ACTIU" NUMBER(10,0), 
	"ENTITATID" NUMBER(19,0) NOT NULL ENABLE, 
	"TIPUS" NUMBER(19,0), 
	 PRIMARY KEY ("PLUGINID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" 
 LOB ("PROPIETATS") STORE AS SECUREFILE (
  TABLESPACE "INTERDOCTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

ALTER TABLE "INTERDOC"."ITD_PLUGIN" ADD CONSTRAINT "ITD_PLUENT_ENTID_FK" FOREIGN KEY ("ENTITATID")
	  REFERENCES "INTERDOC"."ITD_ENTITAT" ("ENTITATID") ENABLE;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100789" ON "INTERDOC"."ITD_PLUGIN" ("PLUGINID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
  CREATE UNIQUE INDEX "INTERDOC"."SYS_IL0000242335C00003$$" ON "INTERDOC"."ITD_PLUGIN" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "INTERDOC"."ITD_PLUGIN_ENTITATID_FK_I" ON "INTERDOC"."ITD_PLUGIN" ("ENTITATID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_REFERENCIA" 
   (	"REFERENCIAID" NUMBER(19,0) NOT NULL ENABLE, 
	"CSVIDENTIFICADOR" VARCHAR2(255), 
	"UUID" VARCHAR2(255), 
	"DIRECCIO" VARCHAR2(255), 
	"HASH" VARCHAR2(255), 
	"EMISOR" VARCHAR2(50) NOT NULL ENABLE, 
	"RECEPTOR" VARCHAR2(50) NOT NULL ENABLE, 
	"URLVISIBLE" VARCHAR2(255), 
	"DATACREACIO" TIMESTAMP (6), 
	"REFERENCIA" VARCHAR2(255), 
	"ENTITATID" NUMBER(19,0), 
	"INFOSIGNATURAID" NUMBER(19,0), 
	"INFOARXIUID" NUMBER(19,0), 
	"FORMATFIRMA" VARCHAR2(5), 
	"FITXERID" NUMBER(19,0), 
	"NUMEROREGISTRE" VARCHAR2(255), 
	 PRIMARY KEY ("REFERENCIAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;

ALTER TABLE "INTERDOC"."ITD_REFERENCIA" ADD CONSTRAINT "ITD_REFENT_ENTID_FK" FOREIGN KEY ("ENTITATID")
	  REFERENCES "INTERDOC"."ITD_ENTITAT" ("ENTITATID") ENABLE;
  ALTER TABLE "INTERDOC"."ITD_REFERENCIA" ADD CONSTRAINT "ITD_REFINF_INFOSIGNATU_FK" FOREIGN KEY ("INFOSIGNATURAID")
	  REFERENCES "INTERDOC"."ITD_INFOSIGNATURA" ("INFOSIGNATURAID") ENABLE;
  ALTER TABLE "INTERDOC"."ITD_REFERENCIA" ADD CONSTRAINT "ITD_REFINF_INFOARXIU_FK" FOREIGN KEY ("INFOARXIUID")
	  REFERENCES "INTERDOC"."ITD_INFOARXIU" ("INFOARXIUID") ENABLE;
  ALTER TABLE "INTERDOC"."ITD_REFERENCIA" ADD CONSTRAINT "ITD_REFFIT_FITXERID_FK" FOREIGN KEY ("FITXERID")
	  REFERENCES "INTERDOC"."ITD_FITXER" ("FITXERID") ENABLE;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100793" ON "INTERDOC"."ITD_REFERENCIA" ("REFERENCIAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
  CREATE INDEX "INTERDOC"."ITD_REFERENCIA_ENTITATID_FK_I" ON "INTERDOC"."ITD_REFERENCIA" ("ENTITATID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
  CREATE INDEX "INTERDOC"."ITD_REFERENCIA_INFOARXIUID_FK_I" ON "INTERDOC"."ITD_REFERENCIA" ("INFOARXIUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
  CREATE INDEX "INTERDOC"."ITD_REFERENCIA_INFOSIGNATURAID_FK_I" ON "INTERDOC"."ITD_REFERENCIA" ("INFOSIGNATURAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
  CREATE INDEX "INTERDOC"."ITD_REFERENCIA_FITXERID_FK_I" ON "INTERDOC"."ITD_REFERENCIA" ("FITXERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_REFERENCIAXML" 
   (	"REFERENCIAXMLID" NUMBER(19,0) NOT NULL ENABLE, 
	"RESULTAT" CLOB, 
	"DATACREACIO" TIMESTAMP (6), 
	"REFERENCIAID" NUMBER(19,0), 
	 PRIMARY KEY ("REFERENCIAXMLID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" 
 LOB ("RESULTAT") STORE AS SECUREFILE (
  TABLESPACE "INTERDOCTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

ALTER TABLE "INTERDOC"."ITD_REFERENCIAXML" ADD CONSTRAINT "ITD_RXMREF_REFID_FK" FOREIGN KEY ("REFERENCIAID")
	  REFERENCES "INTERDOC"."ITD_REFERENCIA" ("REFERENCIAID") ENABLE;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100795" ON "INTERDOC"."ITD_REFERENCIAXML" ("REFERENCIAXMLID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
  CREATE UNIQUE INDEX "INTERDOC"."SYS_IL0000242341C00002$$" ON "INTERDOC"."ITD_REFERENCIAXML" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "INTERDOC"."ITD_REFXML_REFERENCIAID_FK_I" ON "INTERDOC"."ITD_REFERENCIAXML" ("REFERENCIAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INTERDOCTS" ;
;

CREATE TABLE "INTERDOC"."ITD_TRAZA" 
   (	"TRAZAID" NUMBER(19,0) NOT NULL ENABLE, 
	"NOM" VARCHAR2(255), 
	"VALOR" VARCHAR2(255), 
	"DATACREACIO" TIMESTAMP (6), 
	"REFERENCIAID" NUMBER(19,0), 
	 PRIMARY KEY ("TRAZAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "INTERDOCTS" ;

ALTER TABLE "INTERDOC"."ITD_TRAZA" ADD CONSTRAINT "ITD_TRAREF_REFID_FK" FOREIGN KEY ("REFERENCIAID")
	  REFERENCES "INTERDOC"."ITD_REFERENCIA" ("REFERENCIAID") ENABLE;

CREATE UNIQUE INDEX "INTERDOC"."SYS_C00100797" ON "INTERDOC"."ITD_TRAZA" ("TRAZAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS" ;
  CREATE INDEX "INTERDOC"."ITD_TRAZA_REFERENCIAID_FK_I" ON "INTERDOC"."ITD_TRAZA" ("REFERENCIAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "INTERDOCTS" ;
;

CREATE SEQUENCE INTERDOC.ITD_ACCES_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_APLICACIO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_ENTITAT_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_FITXER_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_INFOARXIU_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_INFOSIGNATURA_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_LOG_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_METADADA_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_PETICIOATERCER_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_PLUGIN_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_PROCEDIMENT_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_REFERENCIA_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_REFXML_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_TRAZA_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE INTERDOC.ITD_UNITATORGANICA_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;