package es.caib.interdoc.ws.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5.redhat-00001
 * 2023-05-29T13:29:54.686+02:00
 * Generated source version: 3.2.5.redhat-00001
 *
 */
@WebService(targetNamespace = "http://impl.ws.interna.api.interdoc.caib.es/", name = "CSVQueryDocumentMtomWs")
@XmlSeeAlso({ObjectFactory.class})
public interface CSVQueryDocumentMtomWs {

    @WebMethod
    @RequestWrapper(localName = "csvQueryDocument", targetNamespace = "http://impl.ws.interna.api.interdoc.caib.es/", className = "es.caib.interdoc.ws.api.CsvQueryDocument")
    @ResponseWrapper(localName = "csvQueryDocumentResponse", targetNamespace = "http://impl.ws.interna.api.interdoc.caib.es/", className = "es.caib.interdoc.ws.api.CsvQueryDocumentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String csvQueryDocument(
        @WebParam(name = "csvQueryDocumentRequest", targetNamespace = "")
        es.caib.interdoc.ws.api.CSVQueryDocumentRequest csvQueryDocumentRequest
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "csvQueryDocumentSecurity", targetNamespace = "http://impl.ws.interna.api.interdoc.caib.es/", className = "es.caib.interdoc.ws.api.CsvQueryDocumentSecurity")
    @ResponseWrapper(localName = "csvQueryDocumentSecurityResponse", targetNamespace = "http://impl.ws.interna.api.interdoc.caib.es/", className = "es.caib.interdoc.ws.api.CsvQueryDocumentSecurityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String csvQueryDocumentSecurity(
        @WebParam(name = "csvQueryDocumentSecurityRequest", targetNamespace = "")
        es.caib.interdoc.ws.api.CSVQueryDocumentSecurityRequest csvQueryDocumentSecurityRequest
    ) throws Exception_Exception;
}
