package es.caib.interdoc.ws.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5.redhat-00001
 * 2023-05-29T13:29:54.700+02:00
 * Generated source version: 3.2.5.redhat-00001
 *
 */
@WebServiceClient(name = "CSVQueryDocumentMtomWsService",
                  wsdlLocation = "file:/c:/Dades/Programacio/interdocProjecte/interdoc/interdoc-ws/interdoc-ws-api/src/main/resources/wsdl/CSVQueryDocumentMtomWs.wsdl",
                  targetNamespace = "http://impl.ws.interna.api.interdoc.caib.es/")
public class CSVQueryDocumentMtomWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.interna.api.interdoc.caib.es/", "CSVQueryDocumentMtomWsService");
    public final static QName CSVQueryDocumentMtomWs = new QName("http://impl.ws.interna.api.interdoc.caib.es/", "CSVQueryDocumentMtomWs");
    static {
        URL url = null;
        try {
            url = new URL("file:/c:/Dades/Programacio/interdocProjecte/interdoc/interdoc-ws/interdoc-ws-api/src/main/resources/wsdl/CSVQueryDocumentMtomWs.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CSVQueryDocumentMtomWsService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/c:/Dades/Programacio/interdocProjecte/interdoc/interdoc-ws/interdoc-ws-api/src/main/resources/wsdl/CSVQueryDocumentMtomWs.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CSVQueryDocumentMtomWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CSVQueryDocumentMtomWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CSVQueryDocumentMtomWsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CSVQueryDocumentMtomWsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CSVQueryDocumentMtomWsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CSVQueryDocumentMtomWsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CSVQueryDocumentMtomWs
     */
    @WebEndpoint(name = "CSVQueryDocumentMtomWs")
    public CSVQueryDocumentMtomWs getCSVQueryDocumentMtomWs() {
        return super.getPort(CSVQueryDocumentMtomWs, CSVQueryDocumentMtomWs.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CSVQueryDocumentMtomWs
     */
    @WebEndpoint(name = "CSVQueryDocumentMtomWs")
    public CSVQueryDocumentMtomWs getCSVQueryDocumentMtomWs(WebServiceFeature... features) {
        return super.getPort(CSVQueryDocumentMtomWs, CSVQueryDocumentMtomWs.class, features);
    }

}
