
package es.caib.interdoc.ws.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5.redhat-00001
 * 2023-05-29T13:29:54.651+02:00
 * Generated source version: 3.2.5.redhat-00001
 */

@WebFault(name = "Exception", targetNamespace = "http://impl.ws.interdoc.caib.es/")
public class Exception_Exception extends java.lang.Exception {

    private es.caib.interdoc.ws.api.Exception exception;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, es.caib.interdoc.ws.api.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, es.caib.interdoc.ws.api.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public es.caib.interdoc.ws.api.Exception getFaultInfo() {
        return this.exception;
    }
}
