package es.caib.interdoc.ws.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5.redhat-00001
 * 2023-03-28T15:30:45.276+02:00
 * Generated source version: 3.2.5.redhat-00001
 *
 */
@WebServiceClient(name = "ObtenerReferenciaWsService",
                  wsdlLocation = "file:/c:/Dades/Programacio/interdocProjecte/interdoc/interdoc-ws/interdoc-ws-api/src/main/resources/wsdl/ObtenerReferenciaWs.wsdl",
                  targetNamespace = "http://impl.ws.interna.api.interdoc.caib.es/")
public class ObtenerReferenciaWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.interna.api.interdoc.caib.es/", "ObtenerReferenciaWsService");
    public final static QName ObtenerReferenciaWs = new QName("http://impl.ws.interna.api.interdoc.caib.es/", "ObtenerReferenciaWs");
    static {
        URL url = null;
        try {
            url = new URL("file:/c:/Dades/Programacio/interdocProjecte/interdoc/interdoc-ws/interdoc-ws-api/src/main/resources/wsdl/ObtenerReferenciaWs.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ObtenerReferenciaWsService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/c:/Dades/Programacio/interdocProjecte/interdoc/interdoc-ws/interdoc-ws-api/src/main/resources/wsdl/ObtenerReferenciaWs.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ObtenerReferenciaWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ObtenerReferenciaWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ObtenerReferenciaWsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ObtenerReferenciaWsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ObtenerReferenciaWsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ObtenerReferenciaWsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ObtenerReferenciaWs
     */
    @WebEndpoint(name = "ObtenerReferenciaWs")
    public ObtenerReferenciaWs getObtenerReferenciaWs() {
        return super.getPort(ObtenerReferenciaWs, ObtenerReferenciaWs.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ObtenerReferenciaWs
     */
    @WebEndpoint(name = "ObtenerReferenciaWs")
    public ObtenerReferenciaWs getObtenerReferenciaWs(WebServiceFeature... features) {
        return super.getPort(ObtenerReferenciaWs, ObtenerReferenciaWs.class, features);
    }

}
