/*
 * API REST INTERNA de interdoc
 * Conjunt de Serveis REST de interdoc per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.interdoc.apiinterna.client.api;

import es.caib.interdoc.apiinterna.client.services.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CarregarDocumentApi
 */
@Ignore
public class CarregarDocumentApiTest {

    private final CarregarDocumentApi api = new CarregarDocumentApi();

    /**
     * Carrega un document
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void carregarTest() throws ApiException {
        String response = api.carregar();

        // TODO: test validations
    }
}
