/*
 * API REST INTERNA de interdoc
 * Conjunt de Serveis REST de interdoc per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.interdoc.apiinterna.client.api;

import es.caib.interdoc.apiinterna.client.services.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DescarregarDocumentApi
 */
@Ignore
public class DescarregarDocumentApiTest {

    private final DescarregarDocumentApi api = new DescarregarDocumentApi();

    /**
     * Descarrega un document a partir de la seva referencia
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void descarregarTest() throws ApiException {
        String response = api.descarregar();

        // TODO: test validations
    }
    /**
     * Descarrega un document
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void descarregar1Test() throws ApiException {
        String fileName = null;
        String response = api.descarregar1(fileName);

        // TODO: test validations
    }
}
