/*
 * API REST INTERNA de interdoc
 * Conjunt de Serveis REST de interdoc per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.interdoc.apiinterna.client.api;

import es.caib.interdoc.apiinterna.client.services.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NovaReferenciaApi
 */
@Ignore
public class NovaReferenciaApiTest {

    private final NovaReferenciaApi api = new NovaReferenciaApi();

    /**
     * Crear una nova referencia
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void novaTest() throws ApiException {
        String response = api.nova();

        // TODO: test validations
    }
    /**
     * Crear una nova referencia
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nova1Test() throws ApiException {
        String csv = null;
        String uuid = null;
        String aplicacioId = null;
        String emisor = null;
        String receptor = null;
        String interessats = null;
        String metadades = null;
        String fitxer = null;
        String response = api.nova1(csv, uuid, aplicacioId, emisor, receptor, interessats, metadades, fitxer);

        // TODO: test validations
    }
}
