/*
 * API REST INTERNA de interdoc
 * Conjunt de Serveis REST de interdoc per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.interdoc.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * DescargarDocumentoRequest
 */


public class DescargarDocumentoRequest {
  @JsonProperty("csv")
  private String csv = null;

  @JsonProperty("dir3")
  private String dir3 = null;

  @JsonProperty("recuperacionOriginal")
  private String recuperacionOriginal = null;

  @JsonProperty("documentoEni")
  private String documentoEni = null;

  @JsonProperty("idEni")
  private String idEni = null;

  @JsonProperty("nif")
  private String nif = null;

  @JsonProperty("tipoIdentificacion")
  private String tipoIdentificacion = null;

  @JsonProperty("ip")
  private String ip = null;

  public DescargarDocumentoRequest csv(String csv) {
    this.csv = csv;
    return this;
  }

   /**
   * Get csv
   * @return csv
  **/
  @Schema(description = "")
  public String getCsv() {
    return csv;
  }

  public void setCsv(String csv) {
    this.csv = csv;
  }

  public DescargarDocumentoRequest dir3(String dir3) {
    this.dir3 = dir3;
    return this;
  }

   /**
   * Get dir3
   * @return dir3
  **/
  @Schema(description = "")
  public String getDir3() {
    return dir3;
  }

  public void setDir3(String dir3) {
    this.dir3 = dir3;
  }

  public DescargarDocumentoRequest recuperacionOriginal(String recuperacionOriginal) {
    this.recuperacionOriginal = recuperacionOriginal;
    return this;
  }

   /**
   * Get recuperacionOriginal
   * @return recuperacionOriginal
  **/
  @Schema(description = "")
  public String getRecuperacionOriginal() {
    return recuperacionOriginal;
  }

  public void setRecuperacionOriginal(String recuperacionOriginal) {
    this.recuperacionOriginal = recuperacionOriginal;
  }

  public DescargarDocumentoRequest documentoEni(String documentoEni) {
    this.documentoEni = documentoEni;
    return this;
  }

   /**
   * Get documentoEni
   * @return documentoEni
  **/
  @Schema(description = "")
  public String getDocumentoEni() {
    return documentoEni;
  }

  public void setDocumentoEni(String documentoEni) {
    this.documentoEni = documentoEni;
  }

  public DescargarDocumentoRequest idEni(String idEni) {
    this.idEni = idEni;
    return this;
  }

   /**
   * Get idEni
   * @return idEni
  **/
  @Schema(description = "")
  public String getIdEni() {
    return idEni;
  }

  public void setIdEni(String idEni) {
    this.idEni = idEni;
  }

  public DescargarDocumentoRequest nif(String nif) {
    this.nif = nif;
    return this;
  }

   /**
   * Get nif
   * @return nif
  **/
  @Schema(description = "")
  public String getNif() {
    return nif;
  }

  public void setNif(String nif) {
    this.nif = nif;
  }

  public DescargarDocumentoRequest tipoIdentificacion(String tipoIdentificacion) {
    this.tipoIdentificacion = tipoIdentificacion;
    return this;
  }

   /**
   * Get tipoIdentificacion
   * @return tipoIdentificacion
  **/
  @Schema(description = "")
  public String getTipoIdentificacion() {
    return tipoIdentificacion;
  }

  public void setTipoIdentificacion(String tipoIdentificacion) {
    this.tipoIdentificacion = tipoIdentificacion;
  }

  public DescargarDocumentoRequest ip(String ip) {
    this.ip = ip;
    return this;
  }

   /**
   * Get ip
   * @return ip
  **/
  @Schema(description = "")
  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescargarDocumentoRequest descargarDocumentoRequest = (DescargarDocumentoRequest) o;
    return Objects.equals(this.csv, descargarDocumentoRequest.csv) &&
        Objects.equals(this.dir3, descargarDocumentoRequest.dir3) &&
        Objects.equals(this.recuperacionOriginal, descargarDocumentoRequest.recuperacionOriginal) &&
        Objects.equals(this.documentoEni, descargarDocumentoRequest.documentoEni) &&
        Objects.equals(this.idEni, descargarDocumentoRequest.idEni) &&
        Objects.equals(this.nif, descargarDocumentoRequest.nif) &&
        Objects.equals(this.tipoIdentificacion, descargarDocumentoRequest.tipoIdentificacion) &&
        Objects.equals(this.ip, descargarDocumentoRequest.ip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csv, dir3, recuperacionOriginal, documentoEni, idEni, nif, tipoIdentificacion, ip);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescargarDocumentoRequest {\n");
    
    sb.append("    csv: ").append(toIndentedString(csv)).append("\n");
    sb.append("    dir3: ").append(toIndentedString(dir3)).append("\n");
    sb.append("    recuperacionOriginal: ").append(toIndentedString(recuperacionOriginal)).append("\n");
    sb.append("    documentoEni: ").append(toIndentedString(documentoEni)).append("\n");
    sb.append("    idEni: ").append(toIndentedString(idEni)).append("\n");
    sb.append("    nif: ").append(toIndentedString(nif)).append("\n");
    sb.append("    tipoIdentificacion: ").append(toIndentedString(tipoIdentificacion)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
