/*
 * API REST INTERNA de interdoc
 * Conjunt de Serveis REST de interdoc per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.interdoc.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Fitxer
 */


public class Fitxer {
  @JsonProperty("data")
  private List<byte[]> data = null;

  @JsonProperty("descripcio")
  private String descripcio = null;

  @JsonProperty("mime")
  private String mime = null;

  @JsonProperty("nom")
  private String nom = null;

  @JsonProperty("tamany")
  private Long tamany = null;

  public Fitxer data(List<byte[]> data) {
    this.data = data;
    return this;
  }

  public Fitxer addDataItem(byte[] dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<byte[]>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public List<byte[]> getData() {
    return data;
  }

  public void setData(List<byte[]> data) {
    this.data = data;
  }

  public Fitxer descripcio(String descripcio) {
    this.descripcio = descripcio;
    return this;
  }

   /**
   * Get descripcio
   * @return descripcio
  **/
  @Schema(description = "")
  public String getDescripcio() {
    return descripcio;
  }

  public void setDescripcio(String descripcio) {
    this.descripcio = descripcio;
  }

  public Fitxer mime(String mime) {
    this.mime = mime;
    return this;
  }

   /**
   * Get mime
   * @return mime
  **/
  @Schema(description = "")
  public String getMime() {
    return mime;
  }

  public void setMime(String mime) {
    this.mime = mime;
  }

  public Fitxer nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Get nom
   * @return nom
  **/
  @Schema(description = "")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public Fitxer tamany(Long tamany) {
    this.tamany = tamany;
    return this;
  }

   /**
   * Get tamany
   * @return tamany
  **/
  @Schema(description = "")
  public Long getTamany() {
    return tamany;
  }

  public void setTamany(Long tamany) {
    this.tamany = tamany;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fitxer fitxer = (Fitxer) o;
    return Objects.equals(this.data, fitxer.data) &&
        Objects.equals(this.descripcio, fitxer.descripcio) &&
        Objects.equals(this.mime, fitxer.mime) &&
        Objects.equals(this.nom, fitxer.nom) &&
        Objects.equals(this.tamany, fitxer.tamany);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, descripcio, mime, nom, tamany);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fitxer {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    descripcio: ").append(toIndentedString(descripcio)).append("\n");
    sb.append("    mime: ").append(toIndentedString(mime)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    tamany: ").append(toIndentedString(tamany)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
