/*
 * API REST INTERNA de interdoc
 * Conjunt de Serveis REST de interdoc per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.interdoc.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Metadada
 */


public class Metadada {
  @JsonProperty("clau")
  private String clau = null;

  @JsonProperty("valor")
  private String valor = null;

  @JsonProperty("tipus")
  private String tipus = null;

  public Metadada clau(String clau) {
    this.clau = clau;
    return this;
  }

   /**
   * Get clau
   * @return clau
  **/
  @Schema(description = "")
  public String getClau() {
    return clau;
  }

  public void setClau(String clau) {
    this.clau = clau;
  }

  public Metadada valor(String valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Get valor
   * @return valor
  **/
  @Schema(description = "")
  public String getValor() {
    return valor;
  }

  public void setValor(String valor) {
    this.valor = valor;
  }

  public Metadada tipus(String tipus) {
    this.tipus = tipus;
    return this;
  }

   /**
   * Get tipus
   * @return tipus
  **/
  @Schema(description = "")
  public String getTipus() {
    return tipus;
  }

  public void setTipus(String tipus) {
    this.tipus = tipus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Metadada metadada = (Metadada) o;
    return Objects.equals(this.clau, metadada.clau) &&
        Objects.equals(this.valor, metadada.valor) &&
        Objects.equals(this.tipus, metadada.tipus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clau, valor, tipus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Metadada {\n");
    
    sb.append("    clau: ").append(toIndentedString(clau)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    tipus: ").append(toIndentedString(tipus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
