/*
 * API REST INTERNA de interdoc
 * Conjunt de Serveis REST de interdoc per ser accedits des de l'interior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.interdoc.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.interdoc.apiinterna.client.model.Fitxer;
import es.caib.interdoc.apiinterna.client.model.Metadada;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ObtenerReferenciaRequest
 */


public class ObtenerReferenciaRequest {
  @JsonProperty("csv")
  private String csv = null;

  @JsonProperty("uuid")
  private String uuid = null;

  @JsonProperty("document")
  private Fitxer document = null;

  @JsonProperty("metadades")
  private List<Metadada> metadades = null;

  @JsonProperty("aplicacioId")
  private String aplicacioId = null;

  @JsonProperty("emisor")
  private String emisor = null;

  @JsonProperty("receptor")
  private String receptor = null;

  @JsonProperty("interessats")
  private List<String> interessats = null;

  public ObtenerReferenciaRequest csv(String csv) {
    this.csv = csv;
    return this;
  }

   /**
   * Get csv
   * @return csv
  **/
  @Schema(description = "")
  public String getCsv() {
    return csv;
  }

  public void setCsv(String csv) {
    this.csv = csv;
  }

  public ObtenerReferenciaRequest uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @Schema(description = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public ObtenerReferenciaRequest document(Fitxer document) {
    this.document = document;
    return this;
  }

   /**
   * Get document
   * @return document
  **/
  @Schema(description = "")
  public Fitxer getDocument() {
    return document;
  }

  public void setDocument(Fitxer document) {
    this.document = document;
  }

  public ObtenerReferenciaRequest metadades(List<Metadada> metadades) {
    this.metadades = metadades;
    return this;
  }

  public ObtenerReferenciaRequest addMetadadesItem(Metadada metadadesItem) {
    if (this.metadades == null) {
      this.metadades = new ArrayList<Metadada>();
    }
    this.metadades.add(metadadesItem);
    return this;
  }

   /**
   * Get metadades
   * @return metadades
  **/
  @Schema(description = "")
  public List<Metadada> getMetadades() {
    return metadades;
  }

  public void setMetadades(List<Metadada> metadades) {
    this.metadades = metadades;
  }

  public ObtenerReferenciaRequest aplicacioId(String aplicacioId) {
    this.aplicacioId = aplicacioId;
    return this;
  }

   /**
   * Get aplicacioId
   * @return aplicacioId
  **/
  @Schema(description = "")
  public String getAplicacioId() {
    return aplicacioId;
  }

  public void setAplicacioId(String aplicacioId) {
    this.aplicacioId = aplicacioId;
  }

  public ObtenerReferenciaRequest emisor(String emisor) {
    this.emisor = emisor;
    return this;
  }

   /**
   * Get emisor
   * @return emisor
  **/
  @Schema(description = "")
  public String getEmisor() {
    return emisor;
  }

  public void setEmisor(String emisor) {
    this.emisor = emisor;
  }

  public ObtenerReferenciaRequest receptor(String receptor) {
    this.receptor = receptor;
    return this;
  }

   /**
   * Get receptor
   * @return receptor
  **/
  @Schema(description = "")
  public String getReceptor() {
    return receptor;
  }

  public void setReceptor(String receptor) {
    this.receptor = receptor;
  }

  public ObtenerReferenciaRequest interessats(List<String> interessats) {
    this.interessats = interessats;
    return this;
  }

  public ObtenerReferenciaRequest addInteressatsItem(String interessatsItem) {
    if (this.interessats == null) {
      this.interessats = new ArrayList<String>();
    }
    this.interessats.add(interessatsItem);
    return this;
  }

   /**
   * Get interessats
   * @return interessats
  **/
  @Schema(description = "")
  public List<String> getInteressats() {
    return interessats;
  }

  public void setInteressats(List<String> interessats) {
    this.interessats = interessats;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObtenerReferenciaRequest obtenerReferenciaRequest = (ObtenerReferenciaRequest) o;
    return Objects.equals(this.csv, obtenerReferenciaRequest.csv) &&
        Objects.equals(this.uuid, obtenerReferenciaRequest.uuid) &&
        Objects.equals(this.document, obtenerReferenciaRequest.document) &&
        Objects.equals(this.metadades, obtenerReferenciaRequest.metadades) &&
        Objects.equals(this.aplicacioId, obtenerReferenciaRequest.aplicacioId) &&
        Objects.equals(this.emisor, obtenerReferenciaRequest.emisor) &&
        Objects.equals(this.receptor, obtenerReferenciaRequest.receptor) &&
        Objects.equals(this.interessats, obtenerReferenciaRequest.interessats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csv, uuid, document, metadades, aplicacioId, emisor, receptor, interessats);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObtenerReferenciaRequest {\n");
    
    sb.append("    csv: ").append(toIndentedString(csv)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    metadades: ").append(toIndentedString(metadades)).append("\n");
    sb.append("    aplicacioId: ").append(toIndentedString(aplicacioId)).append("\n");
    sb.append("    emisor: ").append(toIndentedString(emisor)).append("\n");
    sb.append("    receptor: ").append(toIndentedString(receptor)).append("\n");
    sb.append("    interessats: ").append(toIndentedString(interessats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
